In [1]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns

# reading data files
# using encoding = "ISO-8859-1" to avoid pandas encoding error
rounds = pd.read_csv("./rounds2.csv", encoding = "ISO-8859-1")
companies = pd.read_csv("./companies.txt", sep="\t", encoding = "ISO-8859-1")

In [2]:
rounds.head()

,company_permalink,funding_round_permalink,funding_round_type,funding_round_code,funded_at,raised_amount_usd
0,/organization/-fame,/funding-round/9a01d05418af9f794eebff7ace91f638,venture,B,05-01-2015,10000000.0
1,/ORGANIZATION/-QOUNTER,/funding-round/22dacff496eb7acb2b901dec1dfe5633,venture,A,14-10-2014,NaN
2,/organization/-qounter,/funding-round/b44fbb94153f6cdef13083530bb48030,seed,NaN,01-03-2014,700000.0
3,/ORGANIZATION/-THE-ONE-OF-THEM-INC-,/funding-round/650b8f704416801069bb178a1418776b,venture,B,30-01-2014,3406878.0
4,/organization/0-6-com,/funding-round/5727accaeaa57461bd22a9bdd945382d,venture,A,19-03-2008,2000000.0

In [3]:
companies.head()

,permalink,name,homepage_url,category_list,status,country_code,state_code,region,city,founded_at
0,/Organization/-Fame,#fame,http://livfame.com,Media,operating,IND,16,Mumbai,Mumbai,NaN
1,/Organization/-Qounter,:Qounter,http://www.qounter.com,Application Platforms|Real Time|Social Network...,operating,USA,DE,DE - Other,Delaware City,04-09-2014
2,/Organization/-The-One-Of-Them-Inc-,"(THE) ONE of THEM,Inc.",http://oneofthem.jp,Apps|Games|Mobile,operating,NaN,NaN,NaN,NaN,NaN
3,/Organization/0-6-Com,0-6.com,http://www.0-6.com,Curated Web,operating,CHN,22,Beijing,Beijing,01-01-2007
4,/Organization/004-Technologies,004 Technologies,http://004gmbh.de/en/004-interact,Software,operating,USA,IL,"Springfield, Illinois",Champaign,01-01-2010

# Data Cleaning

### We can see that permalink of Companies data frame and Companies_permalink of rounds dataframe are different although they are same
### Let's convert them to lower case

In [4]:
companies["permalink"]=companies["permalink"].str.lower()
rounds["company_permalink"]=rounds["company_permalink"].str.lower()

In [5]:
len(companies["permalink"].unique())

66368

In [6]:
len(rounds["company_permalink"].unique())

66370

Appears like 2 extra companies are there in rounds file which received investment while not listed in companies file let's check them out

In [7]:
rounds.loc[~rounds["company_permalink"].isin(companies["permalink"])]

,company_permalink,funding_round_permalink,funding_round_type,funding_round_code,funded_at,raised_amount_usd
29597,/organization/e-cãbica,/funding-round/8491f74869e4fe8ba9c378394f8fbdea,seed,NaN,01-02-2015,NaN
31863,/organization/energystone-games-çµç³æ¸¸æ,/funding-round/b89553f3d2279c5683ae93f45a21cfe0,seed,NaN,09-08-2014,NaN
45176,/organization/huizuche-com-æ ç§ÿè½¦,/funding-round/8f8a32dbeeb0f831a78702f83af78a36,seed,NaN,18-09-2014,NaN
58473,/organization/magnet-tech-ç£ç³ç§æ,/funding-round/8fc91fbb32bc95e97f151dd0cb4166bf,seed,NaN,16-08-2014,1625585.0
101036,/organization/tipcat-interactive-æ²èÿä¿¡æ¯ç...,/funding-round/41005928a1439cb2d706a43cb661f60f,seed,NaN,06-09-2010,NaN
109969,/organization/weiche-tech-åè½¦ç§æ,/funding-round/f74e457f838b81fa0b29649740f186d8,venture,A,06-09-2015,NaN
113839,/organization/zengame-ç¦ æ¸¸ç§æ,/funding-round/6ba28fb4f3eadf5a9c6c81bc5dde6cdf,seed,NaN,17-07-2010,NaN

Seems like problemiswith encoding.By converting into english

In [8]:
rounds['company_permalink'] = rounds.company_permalink.str.encode('utf-8').str.decode('ascii', 'ignore')
rounds.loc[~rounds['company_permalink'].isin(companies['permalink']), :]

,company_permalink,funding_round_permalink,funding_round_type,funding_round_code,funded_at,raised_amount_usd
77,/organization/10north,/funding-round/b41ff7de932f8b6e5bbeed3966c0ed6a,equity_crowdfunding,NaN,12-08-2014,NaN
729,/organization/51wofang-,/funding-round/346b9180d276a74e0fbb2825e66c6f5b,venture,A,06-07-2015,5000000.0
2670,/organization/adslinked,/funding-round/449ae54bb63c768c232955ca6911dee4,seed,NaN,29-09-2014,100000.0
3166,/organization/aesthetic-everything-social-network,/funding-round/62593455f1a69857ed05d5734cc04132,equity_crowdfunding,NaN,12-10-2014,NaN
3291,/organization/affluent-attach-club-2,/funding-round/626678bdf1654bc4df9b1b34647a4df1,seed,NaN,15-10-2014,100000.0
4568,/organization/allgu-outlet,/funding-round/49e8a9b54ed19c8505ca92dc031a8e9c,venture,NaN,17-03-2015,1400000.0
8097,/organization/asiansbook,/funding-round/3f243ab92b4fe397d41b4734a17ca5f0,seed,NaN,15-09-2014,100000.0
8652,/organization/atlye-gri,/funding-round/75bdeacd95a647108aa4bc480e77894d,grant,NaN,01-11-2012,13940.0
9784,/organization/axgaz,/funding-round/511a41181aaf193bbd419babfb8d66e9,venture,NaN,06-07-2015,4094392.0
14311,/organization/boral-bikes-incorporated,/funding-round/be79575bf4b5b5d6fa64670800a3ca5e,seed,NaN,26-02-2015,NaN
14798,/organization/brasil-oznio,/funding-round/4e0dd70413b121d23274187704e2d91b,seed,NaN,01-07-2015,799686.0
14951,/organization/bricopriv-com,/funding-round/c14e573c4cea05d355a20b5ba6b0d12d,undisclosed,NaN,24-06-2015,2809272.0
15384,/organization/brv,/funding-round/978b27fe5c90372b11adbe33c75cdd03,seed,NaN,31-12-2014,1500.0
16018,/organization/bhner-eh-gmbh,/funding-round/21fde9aaef25f3e1889b8662d7540eda,seed,NaN,18-10-2010,NaN
16624,/organization/canal-da-pea,/funding-round/a16902fe6bd5e67a44dd222ac209fa7e,seed,NaN,19-06-2013,NaN
16839,/organization/cappt,/funding-round/b2b88b247a67469bc8a2df8510078290,convertible_note,NaN,01-09-2014,20228.0
23210,/organization/contrato-rpido,/funding-round/33fe7ab355ca20d8993d8dbe3dcd62d2,seed,NaN,01-03-2015,NaN
23518,/organization/cop-active-ltd,/funding-round/962d2256a1d52ffd07536d03cd90e5b3,seed,NaN,15-02-2015,154028.0
24932,/organization/crme-ciseaux,/funding-round/0aeedf03903b6ff7a7c5d02871842588,equity_crowdfunding,NaN,05-04-2014,276163.0
24933,/organization/crme-ciseaux,/funding-round/c05eea4d4b53eac40f29b4ea9ea67838,equity_crowdfunding,NaN,05-04-2014,276163.0
27110,/organization/desafo-tctico,/funding-round/32109a690a936b7678359619734b8cf9,convertible_note,NaN,02-08-2013,NaN
29597,/organization/e-cbica,/funding-round/8491f74869e4fe8ba9c378394f8fbdea,seed,NaN,01-02-2015,NaN
31863,/organization/energystone-games-,/funding-round/b89553f3d2279c5683ae93f45a21cfe0,seed,NaN,09-08-2014,NaN
33069,/organization/etool-io,/funding-round/3575ca572169fb7b320665767250355a,seed,NaN,16-02-2014,26000.0
37562,/organization/freem,/funding-round/34d9e77d186da2e69b68f371a3f4926e,convertible_note,NaN,16-04-2015,60000.0
37876,/organization/frquentiel,/funding-round/b0778e93110786d599ce8a4788adda9d,undisclosed,NaN,13-03-2015,NaN
39460,/organization/gesto-sade-e-tecnologia-3,/funding-round/f56dcf159f31717b4b4ddd91f732e881,venture,NaN,01-04-2013,NaN
42221,/organization/grfica-en-lnea,/funding-round/cb747fc6c90fa66ebc3ebe25d3377358,equity_crowdfunding,NaN,05-05-2014,150000.0
45176,/organization/huizuche-com-,/funding-round/8f8a32dbeeb0f831a78702f83af78a36,seed,NaN,18-09-2014,NaN
46281,/organization/ignia-bienes-races,/funding-round/ad8b2bf09fda2a09dcdd2ed2a86d0d9c,venture,NaN,01-09-2008,NaN
...,...,...,...,...,...,...
58474,/organization/magnet-tech-,/funding-round/be2fb8789ec4e1902c2a7e1f7313ad3d,venture,A,16-01-2015,NaN
60960,/organization/mercado-electrnico,/funding-round/e4a31c7eb3546cc2bc6eb0c8d05625d4,private_equity,NaN,10-03-2015,9707638.0
62172,/organization/ming-yazlm,/funding-round/b510e4822c0f1b4977cf988e4c5054d0,grant,NaN,04-04-2013,52583.0
63761,/organization/monnier-frres,/funding-round/606655ce25b330ee620137c09af4ec21,seed,NaN,30-06-2011,4616139.0
65471,/organization/mdica-santa-carmen-2,/funding-round/bd94fb319f6ec0e2021dcc5bfad03479,seed,NaN,01-06-2013,NaN
73633,/organization/patrofn,/funding-round/a49df2be4369c01a4a16b9356f5640dd,grant,NaN,01-01-2014,42607.0
78497,/organization/prodti-cz,/funding-round/e3e7909a3c46b470a35fcaf469bdbcae,seed,NaN,01-01-2014,NaN
79281,/organization/przewietl-pl,/funding-round/9fe8ed2986d279646cbcdb72c6c5128a,seed,NaN,01-01-2014,NaN
85619,/organization/salo-vip,/funding-round/6cc488b6bee6c0741491ef71b953dbc6,grant,NaN,01-10-2014,81462.0
85996,/organization/satlite-distribuidora-de-petrleo,/funding-round/a99b1d7625b01c9af80d622e61aaa511,venture,NaN,13-04-2004,NaN
90328,/organization/skar-is,/funding-round/4569a387b074bdc097442f9753914289,seed,NaN,25-06-2014,392492.0
91932,/organization/socit-internationale-de-plantati...,/funding-round/4f6d8e2551eb84c3b5c8234d19b63944,venture,NaN,22-06-2005,14300000.0
97158,/organization/slfar-studios,/funding-round/69c192af02bf6e34dd7210298cecdc3b,seed,NaN,11-11-2015,2100000.0
97571,/organization/talentsigned,/funding-round/b5e611e4c9f4f4ac6b9df67628a90382,seed,NaN,26-09-2014,100000.0
99945,/organization/the-vision-lab-,/funding-round/f0d1dc9c2fc5784065990cebcc4c3515,convertible_note,NaN,22-04-2015,100000.0
100588,/organization/th-gii-di-ng,/funding-round/a49012d798c32ae6c113b8234bdcf804,venture,NaN,28-05-2007,3500000.0
101036,/organization/tipcat-interactive-,/funding-round/41005928a1439cb2d706a43cb661f60f,seed,NaN,06-09-2010,NaN
104092,/organization/tximo,/funding-round/574466178e0b9e182f1e541c6313ea27,venture,NaN,06-09-2015,4600000.0
104093,/organization/to-conejo,/funding-round/f7559463034c712e16100e9466a93057,convertible_note,NaN,01-05-2014,22930.0
105508,/organization/vacation-bnb,/funding-round/f9cc0781977926a4132d6a0f87b0f774,seed,NaN,05-10-2014,100000.0
108953,/organization/v-de-txi,/funding-round/5fe845b41da2eaa8842feb65bb4d1f08,seed,NaN,10-12-2013,517241.0
108954,/organization/vnder-sports-network,/funding-round/63e91de54ea7451b1e2e89ffa6d37443,seed,NaN,13-04-2014,NaN
109968,/organization/weiche-tech-,/funding-round/27b0cd2e0b75cbceb717343ea86c2c28,angel,NaN,16-06-2014,NaN
109969,/organization/weiche-tech-,/funding-round/f74e457f838b81fa0b29649740f186d8,venture,A,06-09-2015,NaN
110516,/organization/whites-holdings,/funding-round/7407f06542934e7dd12beaacc71e8fdc,undisclosed,NaN,16-01-2015,NaN
110545,/organization/whodats-spaces,/funding-round/d5d6db3d1e6c54d71a63b3aa0c9278e6,seed,NaN,28-10-2014,30000.0
113839,/organization/zengame-,/funding-round/6ba28fb4f3eadf5a9c6c81bc5dde6cdf,seed,NaN,17-07-2010,NaN
114946,/organization/eron,/funding-round/59f4dce44723b794f21ded3daed6e4fe,venture,A,01-08-2014,NaN
114947,/organization/asys-2,/funding-round/35f09d0794651719b02bbfd859ba9ff5,seed,NaN,01-01-2015,18192.0
114948,/organization/novatiff-reklam-ve-tantm-hizmetl...,/funding-round/af942869878d2cd788ef5189b435ebc4,grant,NaN,01-10-2013,14851.0

In [9]:
companies['permalink'] = companies.permalink.str.encode('utf-8').str.decode('ascii', 'ignore')

In [10]:
print(len(companies["permalink"].unique()))
print(len(rounds["company_permalink"].unique()))

66368
66368

In [11]:
rounds.to_csv("rounds_new.csv", sep=',', index=False)

# write companies file
companies.to_csv("companies_new.csv", sep='\t', index=False)

In [12]:
rounds = pd.read_csv("rounds_new.csv", encoding = "ISO-8859-1")
companies = pd.read_csv("companies_new.csv", sep="\t", encoding = "ISO-8859-1")

# Missing Value Treatment,Merging and selecting appropriate columns

In [13]:
# missing values in companies df
(companies.isnull().sum()/len(companies.index))*100

permalink         0.000000
name              0.001507
homepage_url      7.621143
category_list     4.743250
status            0.000000
country_code     10.483968
state_code       12.878194
region           12.099204
city             12.096191
founded_at       22.934245
dtype: float64

In [14]:
(rounds.isnull().sum()/len(rounds.index))*100

company_permalink           0.000000
funding_round_permalink     0.000000
funding_round_type          0.000000
funding_round_code         72.909725
funded_at                   0.000000
raised_amount_usd          17.390321
dtype: float64

In [15]:
master = pd.merge(companies, rounds, how="inner", left_on="permalink", right_on="company_permalink")
master.head()

,permalink,name,homepage_url,category_list,status,country_code,state_code,region,city,founded_at,company_permalink,funding_round_permalink,funding_round_type,funding_round_code,funded_at,raised_amount_usd
0,/organization/-fame,#fame,http://livfame.com,Media,operating,IND,16,Mumbai,Mumbai,NaN,/organization/-fame,/funding-round/9a01d05418af9f794eebff7ace91f638,venture,B,05-01-2015,10000000.0
1,/organization/-qounter,:Qounter,http://www.qounter.com,Application Platforms|Real Time|Social Network...,operating,USA,DE,DE - Other,Delaware City,04-09-2014,/organization/-qounter,/funding-round/22dacff496eb7acb2b901dec1dfe5633,venture,A,14-10-2014,NaN
2,/organization/-qounter,:Qounter,http://www.qounter.com,Application Platforms|Real Time|Social Network...,operating,USA,DE,DE - Other,Delaware City,04-09-2014,/organization/-qounter,/funding-round/b44fbb94153f6cdef13083530bb48030,seed,NaN,01-03-2014,700000.0
3,/organization/-the-one-of-them-inc-,"(THE) ONE of THEM,Inc.",http://oneofthem.jp,Apps|Games|Mobile,operating,NaN,NaN,NaN,NaN,NaN,/organization/-the-one-of-them-inc-,/funding-round/650b8f704416801069bb178a1418776b,venture,B,30-01-2014,3406878.0
4,/organization/0-6-com,0-6.com,http://www.0-6.com,Curated Web,operating,CHN,22,Beijing,Beijing,01-01-2007,/organization/0-6-com,/funding-round/5727accaeaa57461bd22a9bdd945382d,venture,A,19-03-2008,2000000.0

In [16]:
master =  master.drop(['company_permalink'], axis=1)

In [17]:
(master.isnull().sum()/len(master.index))*100

permalink                   0.000000
name                        0.000870
homepage_url                5.336280
category_list               2.966533
status                      0.000000
country_code                7.549435
state_code                  9.522484
region                      8.844792
city                        8.842182
founded_at                 17.852265
funding_round_permalink     0.000000
funding_round_type          0.000000
funding_round_code         72.909725
funded_at                   0.000000
raised_amount_usd          17.390321
dtype: float64

In [18]:
master =  master.drop(['funding_round_code'], axis=1)

In [19]:
master = master.drop(['homepage_url', 'founded_at', 'state_code', 'region', 'city'], axis=1)
master.head()

,permalink,name,category_list,status,country_code,funding_round_permalink,funding_round_type,funded_at,raised_amount_usd
0,/organization/-fame,#fame,Media,operating,IND,/funding-round/9a01d05418af9f794eebff7ace91f638,venture,05-01-2015,10000000.0
1,/organization/-qounter,:Qounter,Application Platforms|Real Time|Social Network...,operating,USA,/funding-round/22dacff496eb7acb2b901dec1dfe5633,venture,14-10-2014,NaN
2,/organization/-qounter,:Qounter,Application Platforms|Real Time|Social Network...,operating,USA,/funding-round/b44fbb94153f6cdef13083530bb48030,seed,01-03-2014,700000.0
3,/organization/-the-one-of-them-inc-,"(THE) ONE of THEM,Inc.",Apps|Games|Mobile,operating,NaN,/funding-round/650b8f704416801069bb178a1418776b,venture,30-01-2014,3406878.0
4,/organization/0-6-com,0-6.com,Curated Web,operating,CHN,/funding-round/5727accaeaa57461bd22a9bdd945382d,venture,19-03-2008,2000000.0

In [20]:
master.shape

(114949, 9)

In [21]:
master['raised_amount_usd'].describe()

count    9.495900e+04
mean     1.042687e+07
std      1.148212e+08
min      0.000000e+00
25%      3.225000e+05
50%      1.680511e+06
75%      7.000000e+06
max      2.127194e+10
Name: raised_amount_usd, dtype: float64

In [22]:
master =master[~np.isnan(master['raised_amount_usd'])]
(master.isnull().sum()/len(master.index))*100

permalink                  0.000000
name                       0.001053
category_list              1.099422
status                     0.000000
country_code               6.161607
funding_round_permalink    0.000000
funding_round_type         0.000000
funded_at                  0.000000
raised_amount_usd          0.000000
dtype: float64

In [23]:
country_codes = master['country_code'].astype('category')

# displaying frequencies of each category
100*(master['country_code'].value_counts()/len(master.index))

USA    65.342937
GBR     5.285439
CAN     2.754873
CHN     2.029297
IND     1.736539
FRA     1.528028
ISR     1.436409
ESP     1.131014
DEU     1.097316
AUS     0.683453
RUS     0.619215
IRL     0.592887
SWE     0.589728
SGP     0.574985
NLD     0.560242
JPN     0.510747
BRA     0.508641
ITA     0.508641
CHE     0.460199
KOR     0.454933
CHL     0.454933
FIN     0.402279
DNK     0.330669
ARG     0.312767
BEL     0.308554
HKG     0.263272
TUR     0.206405
NOR     0.201139
BGR     0.200086
MEX     0.199033
         ...
MCO     0.002106
ZMB     0.002106
TUN     0.002106
BLZ     0.002106
BAH     0.002106
KWT     0.002106
CIV     0.002106
ALB     0.002106
DOM     0.002106
SOM     0.001053
MNE     0.001053
LAO     0.001053
TGO     0.001053
UZB     0.001053
KNA     0.001053
GRD     0.001053
HND     0.001053
QAT     0.001053
DZA     0.001053
OMN     0.001053
SYC     0.001053
GGY     0.001053
MKD     0.001053
DMA     0.001053
PSE     0.001053
IRN     0.001053
SEN     0.001053
PRY     0.001053
BRB     0.001053
BLM     0.001053
Name: country_code, Length: 134, dtype: float64

In [24]:
master = master[~pd.isnull(master['country_code'])]

In [25]:
(master.isnull().sum()/len(master.index))*100

permalink                  0.000000
name                       0.001122
category_list              0.649773
status                     0.000000
country_code               0.000000
funding_round_permalink    0.000000
funding_round_type         0.000000
funded_at                  0.000000
raised_amount_usd          0.000000
dtype: float64

In [26]:
# writing the clean dataframe to an another file
master.to_csv("master_df.csv", sep=',', index=False)

In [27]:
df = pd.read_csv("master_df.csv", sep=",", encoding="ISO-8859-1")
df.head()

,permalink,name,category_list,status,country_code,funding_round_permalink,funding_round_type,funded_at,raised_amount_usd
0,/organization/-fame,#fame,Media,operating,IND,/funding-round/9a01d05418af9f794eebff7ace91f638,venture,05-01-2015,10000000.0
1,/organization/-qounter,:Qounter,Application Platforms|Real Time|Social Network...,operating,USA,/funding-round/b44fbb94153f6cdef13083530bb48030,seed,01-03-2014,700000.0
2,/organization/0-6-com,0-6.com,Curated Web,operating,CHN,/funding-round/5727accaeaa57461bd22a9bdd945382d,venture,19-03-2008,2000000.0
3,/organization/01games-technology,01Games Technology,Games,operating,HKG,/funding-round/7d53696f2b4f607a2f2a8cbb83d01839,undisclosed,01-07-2014,41250.0
4,/organization/0ndine-biomedical-inc,Ondine Biomedical Inc.,Biotechnology,operating,CAN,/funding-round/2b9d3ac293d5cdccbecff5c8cb0f327d,seed,11-09-2009,43360.0

In [28]:
df["funding_round_type"].value_counts()

venture                  48111
seed                     21233
debt_financing            6533
angel                     4427
grant                     1979
private_equity            1835
undisclosed               1352
convertible_note          1326
equity_crowdfunding       1136
post_ipo_equity            601
product_crowdfunding       332
post_ipo_debt              151
non_equity_assistance       63
secondary_market            29
Name: funding_round_type, dtype: int64

## There are number of funding types but we need only "Seed","Private equity", "angel", "venture"

In [29]:
df = df[(df["funding_round_type"]=="seed")|
        (df["funding_round_type"]=="venture") |
        (df["funding_round_type"] == "angel") |
        (df["funding_round_type"] == "private_equity")]

In [30]:
df.groupby("funding_round_type")["raised_amount_usd"].mean()/1000000

funding_round_type
angel              0.968560
private_equity    73.618564
seed               0.748104
venture           11.735780
Name: raised_amount_usd, dtype: float64

Let's go with median  since they are most occuring values and due to it's robust ness

In [31]:
df.groupby("funding_round_type")["raised_amount_usd"].median()/1000000

funding_round_type
angel              0.410737
private_equity    20.000000
seed               0.300000
venture            5.000000
Name: raised_amount_usd, dtype: float64

### We can see that "Private Equity" is beyond while "Angel" and " Seed" are below range. So "Venture" type of funding is more suitable

## Country Wise Analysis

In [32]:
df = df[df.funding_round_type=="venture"]

# group by country codes and compare the total funding amounts
country_wise = df.groupby('country_code')['raised_amount_usd'].sum().sort_values(ascending=False)
print(country_wise)

country_code
USA    4.225108e+11
CHN    3.983542e+10
GBR    2.024563e+10
IND    1.439186e+10
CAN    9.583332e+09
FRA    7.259537e+09
ISR    6.907515e+09
DEU    6.346960e+09
JPN    3.363677e+09
SWE    3.254953e+09
NLD    2.939404e+09
CHE    2.827560e+09
SGP    2.793918e+09
ESP    1.835831e+09
BRA    1.785987e+09
IRL    1.676131e+09
RUS    1.570426e+09
AUS    1.322935e+09
DNK    1.228311e+09
BEL    1.070542e+09
FIN    1.043200e+09
NOR    9.561924e+08
KOR    9.399883e+08
MYS    8.830588e+08
HKG    7.812670e+08
AUT    6.309550e+08
TWN    6.239795e+08
TUR    5.590975e+08
ITA    4.882894e+08
NZL    4.483164e+08
           ...
KWT    1.400000e+07
LIE    1.309172e+07
MNE    1.220000e+07
SVN    1.201751e+07
BGR    1.130000e+07
KAZ    1.100000e+07
GRC    1.074378e+07
BAH    8.900000e+06
TTO    8.500000e+06
SVK    8.241062e+06
BGD    7.002000e+06
LBN    6.455000e+06
GGY    3.960000e+06
TUN    3.920000e+06
SEN    2.860000e+06
HRV    2.633669e+06
UGA    2.500000e+06
PER    2.469270e+06
BWA    2.250000e+06
PAN    2.100000e+06
LAO    2.100000e+06
MAR    1.600000e+06
MUS    1.500000e+06
PRI    1.441901e+06
ECU    9.658500e+05
MCO    6.570000e+05
SAU    5.000000e+05
CMR    3.595610e+05
GTM    3.000000e+05
MMR    2.000000e+05
Name: raised_amount_usd, Length: 97, dtype: float64

In [33]:
top9 = country_wise[0:10]
top9

country_code
USA    4.225108e+11
CHN    3.983542e+10
GBR    2.024563e+10
IND    1.439186e+10
CAN    9.583332e+09
FRA    7.259537e+09
ISR    6.907515e+09
DEU    6.346960e+09
JPN    3.363677e+09
SWE    3.254953e+09
Name: raised_amount_usd, dtype: float64

#### Top3 English Speaking Countries : "USA","GBR","IND"

In [34]:
top3_eng = top9.loc[["USA","GBR","IND"]]
top3_eng.sort_values(ascending=False)

country_code
USA    4.225108e+11
GBR    2.024563e+10
IND    1.439186e+10
Name: raised_amount_usd, dtype: float64

In [35]:
df = df[(df.country_code=='USA') | (df.country_code=='GBR') | (df.country_code=='IND')]
df.head()

,permalink,name,category_list,status,country_code,funding_round_permalink,funding_round_type,funded_at,raised_amount_usd
0,/organization/-fame,#fame,Media,operating,IND,/funding-round/9a01d05418af9f794eebff7ace91f638,venture,05-01-2015,10000000.0
7,/organization/0xdata,H2O.ai,Analytics,operating,USA,/funding-round/3bb2ee4a2d89251a10aaa735b1180e44,venture,09-11-2015,20000000.0
8,/organization/0xdata,H2O.ai,Analytics,operating,USA,/funding-round/ae2a174c06517c2394aed45006322a7e,venture,03-01-2013,1700000.0
9,/organization/0xdata,H2O.ai,Analytics,operating,USA,/funding-round/e1cfcbe1bdf4c70277c5f29a3482f24e,venture,19-07-2014,8900000.0
15,/organization/1-mainstream,1 Mainstream,Apps|Cable|Distribution|Software,acquired,USA,/funding-round/b952cbaf401f310927430c97b68162ea,venture,17-03-2015,5000000.0

In [36]:
df["category_list"]=df["category_list"].to_string()

In [37]:
df["main_category"]=df["category_list"].apply(lambda x : x.split("|")[0])

In [38]:
df = df.drop('category_list', axis=1)
df.head()

,permalink,name,status,country_code,funding_round_permalink,funding_round_type,funded_at,raised_amount_usd,main_category
0,/organization/-fame,#fame,operating,IND,/funding-round/9a01d05418af9f794eebff7ace91f638,venture,05-01-2015,10000000.0,0 ...
7,/organization/0xdata,H2O.ai,operating,USA,/funding-round/3bb2ee4a2d89251a10aaa735b1180e44,venture,09-11-2015,20000000.0,0 ...
8,/organization/0xdata,H2O.ai,operating,USA,/funding-round/ae2a174c06517c2394aed45006322a7e,venture,03-01-2013,1700000.0,0 ...
9,/organization/0xdata,H2O.ai,operating,USA,/funding-round/e1cfcbe1bdf4c70277c5f29a3482f24e,venture,19-07-2014,8900000.0,0 ...
15,/organization/1-mainstream,1 Mainstream,acquired,USA,/funding-round/b952cbaf401f310927430c97b68162ea,venture,17-03-2015,5000000.0,0 ...

In [39]:
mapping = pd.read_csv("mapping.csv", sep=",")
mapping.head()

,category_list,Automotive & Sports,Blanks,Cleantech / Semiconductors,Entertainment,Health,Manufacturing,"News, Search and Messaging",Others,"Social, Finance, Analytics, Advertising"
0,NaN,0,1,0,0,0,0,0,0,0
1,3D,0,0,0,0,0,1,0,0,0
2,3D Printing,0,0,0,0,0,1,0,0,0
3,3D Technology,0,0,0,0,0,1,0,0,0
4,Accounting,0,0,0,0,0,0,0,0,1

In [40]:
mapping.isnull().sum()

category_list                              1
Automotive & Sports                        0
Blanks                                     0
Cleantech / Semiconductors                 0
Entertainment                              0
Health                                     0
Manufacturing                              0
News, Search and Messaging                 0
Others                                     0
Social, Finance, Analytics, Advertising    0
dtype: int64

In [41]:
mapping = mapping[~pd.isnull(mapping["category_list"])]
mapping.isnull().sum()

category_list                              0
Automotive & Sports                        0
Blanks                                     0
Cleantech / Semiconductors                 0
Entertainment                              0
Health                                     0
Manufacturing                              0
News, Search and Messaging                 0
Others                                     0
Social, Finance, Analytics, Advertising    0
dtype: int64

In [42]:
mapping['category_list'] = mapping['category_list'].str.lower()
df['main_category'] = df['main_category'].str.lower()

In [43]:
mapping['category_list']

1                                      3d
2                             3d printing
3                           3d technology
4                              accounting
5                        active lifestyle
6                            ad targeting
7                      advanced materials
8                        adventure travel
9                             advertising
10                  advertising exchanges
11                   advertising networks
12                  advertising platforms
13                                 advice
14                              aerospace
15                            agriculture
16                  air pollution control
17                             algorithms
18                            all markets
19                           all students
20                    alter0tive medicine
21                                 alumni
22                               a0lytics
23                                android
24                                 angels
25                            animal feed
26             anything capital intensive
27                          app discovery
28                          app marketing
29                             app stores
30     application performance monitoring
                      ...
658                             usability
659                user experience design
660                        user interface
661                             utilities
662               vending and concessions
663                       venture capital
664                             veteri0ry
665                                 video
666                    video conferencing
667                           video games
668                       video on demand
669                       video streaming
670                    virtual workforces
671                                  voip
672                       waste ma0gement
673                                 watch
674                                 water
675                    water purification
676                             wearables
677                          web browsers
678                            web design
679                       web development
680                           web hosting
681                             web tools
682                              weddings
683                             wholesale
684                      wine and spirits
685                              wireless
686                                 women
687                          young adults
Name: category_list, Length: 687, dtype: object

In [44]:
df[~df['main_category'].isin(mapping['category_list'])]

,permalink,name,status,country_code,funding_round_permalink,funding_round_type,funded_at,raised_amount_usd,main_category
0,/organization/-fame,#fame,operating,IND,/funding-round/9a01d05418af9f794eebff7ace91f638,venture,05-01-2015,10000000.0,0 ...
7,/organization/0xdata,H2O.ai,operating,USA,/funding-round/3bb2ee4a2d89251a10aaa735b1180e44,venture,09-11-2015,20000000.0,0 ...
8,/organization/0xdata,H2O.ai,operating,USA,/funding-round/ae2a174c06517c2394aed45006322a7e,venture,03-01-2013,1700000.0,0 ...
9,/organization/0xdata,H2O.ai,operating,USA,/funding-round/e1cfcbe1bdf4c70277c5f29a3482f24e,venture,19-07-2014,8900000.0,0 ...
15,/organization/1-mainstream,1 Mainstream,acquired,USA,/funding-round/b952cbaf401f310927430c97b68162ea,venture,17-03-2015,5000000.0,0 ...
21,/organization/10-minutes-with,10 Minutes With,operating,GBR,/funding-round/0faccbbcc5818dc5326469f13f5a8ac8,venture,09-10-2014,4000000.0,0 ...
25,/organization/1000memories,1000memories,acquired,USA,/funding-round/502bd0e50c27616995e4bdad24605ef8,venture,16-02-2011,2520000.0,0 ...
29,/organization/1000museums-com,1000museums.com,operating,USA,/funding-round/13be128d655076a025221d7fddc90d68,venture,14-10-2009,265940.0,0 ...
30,/organization/1000museums-com,1000museums.com,operating,USA,/funding-round/6aeb32ab3fc05db2b606d7a2466e8c09,venture,15-01-2014,2906832.0,0 ...
31,/organization/1000museums-com,1000museums.com,operating,USA,/funding-round/89317984885b44f02e4befb9dc2e588c,venture,01-08-2014,1500000.0,0 ...
33,/organization/1000museums-com,1000museums.com,operating,USA,/funding-round/fd1b3064232ba9b3cfb5653a619e82e8,venture,05-04-2011,642000.0,0 ...
45,/organization/100health,Redox,operating,USA,/funding-round/502f558bee350299fd1ae503e5b9a124,venture,20-10-2015,3530000.0,0 ...
47,/organization/100plus,100Plus,acquired,USA,/funding-round/b5facb0d9dea2f0352b5834892c88c53,venture,02-11-2011,500000.0,0 ...
48,/organization/1010data,1010data,acquired,USA,/funding-round/482fbf992b48f5c47d0080ab7ec0cb54,venture,08-03-2010,35000000.0,0 ...
52,/organization/10x-genomics,10X Genomics,operating,USA,/funding-round/563923487783bdeb5d0b7872f3d6b99a,venture,12-01-2015,55000000.0,0 ...
53,/organization/10x-technologies,10X Technologies,operating,USA,/funding-round/39c1441d5098875a925577d0f2ad3904,venture,12-01-2015,550000.0,0 ...
58,/organization/11i-solutions,11i Solutions,closed,USA,/funding-round/e07501ed6997290b1bef59406bc300a1,venture,22-03-2011,1800000.0,0 ...
72,/organization/128-technology,128 Technology,operating,USA,/funding-round/fb6216a30cb566ede89e0bee0623a634,venture,16-12-2014,11999347.0,0 ...
76,/organization/1366-technologies,1366 Technologies,operating,USA,/funding-round/2a31dd8a0b006b341cde0f7b721008e6,venture,14-01-2011,2400000.0,0 ...
77,/organization/1366-technologies,1366 Technologies,operating,USA,/funding-round/31e8a281fe0247f5f13f7be8afe47e01,venture,12-12-2013,2500000.0,0 ...
78,/organization/1366-technologies,1366 Technologies,operating,USA,/funding-round/424129ce1235cfab2655ee81305f7c2b,venture,15-10-2013,15000000.0,0 ...
79,/organization/1366-technologies,1366 Technologies,operating,USA,/funding-round/6d3f3797371956ece035b8478c1441b2,venture,09-04-2015,5000000.0,0 ...
80,/organization/1366-technologies,1366 Technologies,operating,USA,/funding-round/786f61aa9866f4471151285f5c56be36,venture,03-02-2010,5150000.0,0 ...
81,/organization/1366-technologies,1366 Technologies,operating,USA,/funding-round/82ace97530965cd2be8f262836b43ff5,venture,27-03-2008,12400000.0,0 ...
82,/organization/1366-technologies,1366 Technologies,operating,USA,/funding-round/ab99fc5a53717b1b53fd6aa5687c5fa9,venture,16-12-2010,6000000.0,0 ...
83,/organization/1366-technologies,1366 Technologies,operating,USA,/funding-round/b09fa4a4c5c5f5f19305c39c94b7d673,venture,19-10-2010,20000000.0,0 ...
86,/organization/140-proof,140 Proof,operating,USA,/funding-round/2dc9ff9c590200195228ce2e153a1423,venture,01-07-2009,3000000.0,0 ...
87,/organization/140-proof,140 Proof,operating,USA,/funding-round/3d40399001b0a2088620030afc533c83,venture,28-04-2011,2500000.0,0 ...
92,/organization/16-mile-solutions,16 Mile Solutions,operating,USA,/funding-round/3a671cf6f08fe5d0a878f5627134384c,venture,11-06-2009,199957.0,0 ...
95,/organization/170-systems,170 Systems,acquired,USA,/funding-round/b84bb882ca873f5fb96535671981196d,venture,16-04-2002,14000000.0,0 ...
...,...,...,...,...,...,...,...,...,...
89036,/organization/zyga-technology,Zyga Technology,operating,USA,/funding-round/487b1d062a5adda324bade159c945d43,venture,16-05-2012,25000000.0,0 ...
89039,/organization/zyga-technology,Zyga Technology,operating,USA,/funding-round/b43977b01d7e4d942e9ad971559de042,venture,02-06-2011,5000000.0,0 ...
89040,/organization/zyga-technology,Zyga Technology,operating,USA,/funding-round/b7561b5b751428e473d118cae37f776d,venture,06-10-2008,5750000.0,0 ...
89041,/organization/zyga-technology,Zyga Technology,operating,USA,/funding-round/f7ad1ad4a268c3ea68fd01a7db2d25ab,venture,20-11-2015,5000000.0,0 ...
89042,/organization/zygo-corporation,Zygo Corporation,acquired,USA,/funding-round/d2c6bee0114056f3018667a9b5ab13ba,venture,24-10-2011,9000000.0,0 ...
89048,/organization/zylie-the-bear,Zylie the Bear,operating,USA,/funding-round/210831899fba3f59921e1ef5c17a95b4,venture,07-06-2012,75000.0,0 ...
89049,/organization/zylun-staffing,Zylun Staffing,operating,USA,/funding-round/a991be2cd93e14d107d6aea8f41b3b4a,venture,28-08-2014,666154.0,0 ...
89050,/organization/zyme-solutions,Zyme Solutions,operating,USA,/funding-round/750e756e0c6e44a04f31e460106e5823,venture,05-03-2009,999999.0,0 ...
89051,/organization/zyme-solutions,Zyme Solutions,operating,USA,/funding-round/882bfc4385f305c46bf0afdb72a9af26,venture,01-05-2014,3000000.0,0 ...
89052,/organization/zyme-solutions,Zyme Solutions,operating,USA,/funding-round/95df0674abfe3b59a0f32ffcc1007853,venture,12-09-2005,3040000.0,0 ...
89054,/organization/zymergen,Zymergen,operating,USA,/funding-round/0f14ff055053208bd3d8eae98c9b3a28,venture,16-06-2015,44000000.0,0 ...
89055,/organization/zymetis,Zymetis,closed,USA,/funding-round/6d3ae270761d1bb03a53e1cbf68a8317,venture,11-01-2010,757464.0,0 ...
89064,/organization/zyncd,Zyncd,operating,GBR,/funding-round/3549f5a481f83610044a4226926acf5a,venture,01-09-2014,144451.0,0 ...
89068,/organization/zynerba-pharmaceuticals,Zynerba Pharmaceuticals,ipo,USA,/funding-round/8992160f6abc8e21563e54a6e97a8922,venture,14-10-2014,13000000.0,0 ...
89069,/organization/zynga,Zynga,ipo,USA,/funding-round/1bc4f7b3a778e5abfbd7131f595f5011,venture,04-11-2009,15187000.0,0 ...
89070,/organization/zynga,Zynga,ipo,USA,/funding-round/5bebd7acdfd44138f81d162f21c532f9,venture,12-10-2010,6337786.0,0 ...
89071,/organization/zynga,Zynga,ipo,USA,/funding-round/66d64809546fe2031d3479161e3c88f9,venture,01-01-2008,10000000.0,0 ...
89072,/organization/zynga,Zynga,ipo,USA,/funding-round/72e4fdf2cfb0cdc0750f90e486722068,venture,18-07-2008,25000000.0,0 ...
89073,/organization/zynga,Zynga,ipo,USA,/funding-round/8411431b5a0389a874e3fae93016c089,venture,24-04-2010,15000000.0,0 ...
89074,/organization/zynga,Zynga,ipo,USA,/funding-round/a6ebc53cf3c0c97d1cdd075f6bbf31fa,venture,18-02-2011,490000000.0,0 ...
89075,/organization/zynga,Zynga,ipo,USA,/funding-round/cf8299f657f7fd4cf01054ee1934109c,venture,14-06-2010,300000000.0,0 ...
89076,/organization/zynga,Zynga,ipo,USA,/funding-round/eb198261da812bc8d3bf475ccec44000,venture,12-02-2008,5026000.0,0 ...
89077,/organization/zyngenia,Zyngenia,operating,USA,/funding-round/55ec03b6fa2e812a2b4a9da5a4555752,venture,09-09-2010,25000000.0,0 ...
89078,/organization/zynstra,Zynstra,operating,GBR,/funding-round/05f43b37c270f5919578281ce803de8f,venture,09-07-2014,8400000.0,0 ...
89079,/organization/zynstra,Zynstra,operating,GBR,/funding-round/129127802dd48be42d6cd45f65895245,venture,12-09-2013,3800000.0,0 ...
89082,/organization/zyomyx-inc,ZYOMYX,operating,USA,/funding-round/4191cb5258d3863b0212d1083881da64,venture,30-06-2013,12000000.0,0 ...
89084,/organization/zyomyx-inc,ZYOMYX,operating,USA,/funding-round/b4fce7f8a13267353d57db09099800e8,venture,11-07-2013,14219999.0,0 ...
89085,/organization/zyomyx-inc,ZYOMYX,operating,USA,/funding-round/ea5b21da6cf999ff4d5667431fe318d7,venture,29-01-2010,555016.0,0 ...
89095,/organization/zyrra,Zyrra,operating,USA,/funding-round/7a0fa791c96c9c447ee54662395beab9,venture,18-10-2012,140500.0,0 ...
89097,/organization/zystor,Zystor,acquired,USA,/funding-round/7ea37c0ff4132b084832039a9380d34e,venture,16-12-2004,8500000.0,0 ...

In [45]:
mapping[~mapping['category_list'].isin(df['main_category'])]

,category_list,Automotive & Sports,Blanks,Cleantech / Semiconductors,Entertainment,Health,Manufacturing,"News, Search and Messaging",Others,"Social, Finance, Analytics, Advertising"
1,3d,0,0,0,0,0,1,0,0,0
2,3d printing,0,0,0,0,0,1,0,0,0
3,3d technology,0,0,0,0,0,1,0,0,0
4,accounting,0,0,0,0,0,0,0,0,1
5,active lifestyle,0,0,0,0,1,0,0,0,0
6,ad targeting,0,0,0,0,0,0,0,0,1
7,advanced materials,0,0,0,0,0,1,0,0,0
8,adventure travel,1,0,0,0,0,0,0,0,0
9,advertising,0,0,0,0,0,0,0,0,1
10,advertising exchanges,0,0,0,0,0,0,0,0,1
11,advertising networks,0,0,0,0,0,0,0,0,1
12,advertising platforms,0,0,0,0,0,0,0,0,1
13,advice,0,0,0,0,0,0,0,1,0
14,aerospace,1,0,0,0,0,0,0,0,0
15,agriculture,0,0,0,0,0,1,0,0,0
16,air pollution control,0,0,1,0,0,0,0,0,0
17,algorithms,0,0,0,0,0,0,0,1,0
18,all markets,0,0,0,0,0,0,0,1,0
19,all students,0,0,0,0,0,0,0,1,0
20,alter0tive medicine,0,0,0,0,1,0,0,0,0
21,alumni,0,0,0,0,0,0,0,1,0
22,a0lytics,0,0,0,0,0,0,0,0,1
23,android,0,0,0,0,0,0,0,0,1
24,angels,0,0,0,0,0,0,0,1,0
25,animal feed,0,0,0,0,1,0,0,0,0
26,anything capital intensive,0,0,0,0,0,0,0,0,1
27,app discovery,0,0,0,0,0,0,1,0,0
28,app marketing,0,0,0,0,0,0,1,0,0
29,app stores,0,0,0,0,0,0,1,0,0
30,application performance monitoring,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...
658,usability,0,0,0,0,0,0,0,1,0
659,user experience design,0,0,0,0,0,0,0,1,0
660,user interface,0,0,0,0,0,0,0,1,0
661,utilities,0,0,0,0,0,0,0,1,0
662,vending and concessions,0,0,0,0,0,0,0,1,0
663,venture capital,0,0,0,0,0,0,0,0,1
664,veteri0ry,0,0,0,0,1,0,0,0,0
665,video,0,0,0,1,0,0,0,0,0
666,video conferencing,0,0,0,1,0,0,0,0,0
667,video games,0,0,0,1,0,0,0,0,0
668,video on demand,0,0,0,1,0,0,0,0,0
669,video streaming,0,0,0,1,0,0,0,0,0
670,virtual workforces,0,0,0,1,0,0,0,0,0
671,voip,0,0,0,1,0,0,0,0,0
672,waste ma0gement,0,0,1,0,0,0,0,0,0
673,watch,0,0,0,0,0,0,0,1,0
674,water,0,0,1,0,0,0,0,0,0
675,water purification,0,0,1,0,0,0,0,0,0
676,wearables,0,0,1,0,0,0,0,0,0
677,web browsers,0,0,0,0,0,0,1,0,0
678,web design,0,0,0,0,0,0,1,0,0
679,web development,0,0,0,0,0,0,0,1,0
680,web hosting,0,0,0,0,0,0,0,1,0
681,web tools,0,0,0,0,0,0,0,1,0
682,weddings,0,0,0,1,0,0,0,0,0
683,wholesale,0,0,0,0,0,0,0,1,0
684,wine and spirits,0,0,0,1,0,0,0,0,0
685,wireless,0,0,0,1,0,0,0,0,0
686,women,0,0,0,0,0,0,0,1,0
687,young adults,0,0,0,0,0,0,0,1,0

In [54]:
mapping['category_list'] = mapping['category_list'].apply(lambda x: x.replace('0', 'na'))

In [55]:
df = pd.merge(df, mapping, how='inner', left_on='main_category', right_on='category_list')

In [56]:
df.shape

(0, 29)